import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Bell,
  BookOpen,
  Briefcase,
  CalendarCheck,
  ClipboardList,
  FileText,
  FolderClosed,
  Gavel,
  Landmark,
  Leaf,
  Library,
  Mail,
  MessageSquare,
  Scale,
  Sparkles,
  Ticket,
  Users,
} from "lucide-react";

export const TILE_ICONS: Record<string, LucideIcon> = {
  ask: MessageSquare,
  library: Library,
  gavel: Gavel,
  file: FileText,
  mail: Mail,
  briefcase: Briefcase,
  sparkles: Sparkles,
  vault: FolderClosed,
  calendar: CalendarCheck,
  ticket: Ticket,
  landmark: Landmark,
  book: BookOpen,
  scale: Scale,
  folder: FolderClosed,
  bell: Bell,
  clipboard: ClipboardList,
  users: Users,
  alert: AlertTriangle,
  leaf: Leaf,
};
